name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    if: "!contains(github.event.head_commit.author.name, 'GITHUB_ACTION')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.11

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18.0.0'
          registry-url: https://registry.npmjs.org/

      - name: Set npm credentials
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Output Run number
        run: echo ${{ github.run_number }}

      - name: Deploy on main branch
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "GITHUB_ACTION"
          npm run publish:release